# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: toantune <toantune@student.42lisboa.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/09 14:32:56 by toantune          #+#    #+#              #
#    Updated: 2023/08/09 15:14:00 by toantune         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = pswap.out

CC = cc

CFLAGS = -Wall -Wextra -Werror

RM = rm -f

FILE = 

all: $(NAME)

clean:
	$(RM) 

fclean: clean
	$(RM) $(NAME)

re: clean all

.PHONY: all clean fclean re
	
